# multiple tests suites
# working example can be found at https://github.com/scottohara/loot

language: node_js
node_js:
  - node

# Cache gems
cache:
  bundler: true
  directories:
    - node_modules


env:
  global:
    - CC_TEST_REPORTER_ID=b14ce19cf604c365b0898c025f2b8698c16902d0af8493473a6d971d9856674f

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter


before_script:
  - ./cc-test-reporter before-build

# Run the test suites
script:
  - make lint
  - npm run coverage

# Pipe the coverage data to Code Climate
after_script:
  - - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT